YongxueHong/ipa

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10055.py

add case rehl7_10055.py
Signed-off-by: micai <micai@dhcp-8-101.nay.redhat.com>

add case rehl7_10055.py

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10040.py

JIRA[ELPPCKVM-802]:Add the polarion case rhel7_10040

JIRA[ELPPCKVM-802]:Add the polarion case rhel7_10040

---

Start2Run.py
monitor.py
runner.py
utils_guest.py
utils_host.py
utils_log.py
utils_migration.py
utils_params.py
vm.py

ELPPCKVM-813: [framework] Update the code lay-out of framework with PEP8

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10022.py

ELPPCKVM-815: [migration] [rhel7_10022] update case rhel7_10022 with PEP8

ELPPCKVM-815: [migration] [rhel7_10022] update case rhel7_10022 with PEP8

---

Start2Run.py
utils_options.py
utils_params.py
virtkvmqe/migration_test_plan/migration/test_requirement/ppc64le/rhel7_58700.yaml
virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114.yaml

1. Could update the parameter of test requirement online.
2. Show the linked test case of given test requirement.
3. Replace the char "yhong" with "mouse" all the yaml file.

ELPPCKVM-812: [framework] Update the option of command "Start2Run":

---

Start2Run.py
utils_options.py
utils_params.py
virtkvmqe/migration_test_plan/migration/test_requirement/ppc64le/rhel7_58700.yaml
virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114.yaml

1. Could update the parameter of test requirement online.
2. Show the linked test case of given test requirement.
3. Replace the char "yhong" with "mouse" all the yaml file.

ELPPCKVM-812: [framework] [PATCH V2] Update the option of command "Start2Run":

---

utils_options.py
utils_params.py

1. Update the patch ELPPCKVM-812 V2.

ELPPCKVM-812 V3: [framework] Update the option of command "Start2Run"

---

utils_options.py
virtkvmqe/migration_test_plan/migration/test_requirement/ppc64le/rhel7_58700.yaml
virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114.yaml

1. Delete the invalid options.

ELPPCKVM-812-V4:Delete the invalid options.

---

Start2Run.py
unattended_installation/ks/RHEL-7-series.ks
unattended_installation/unattended_installation.py
unattended_installation/unattended_installation.yaml
utils_modules.yaml

Add a function of installing guest os.

ELPPCKVM-825: [framework] Add a function of installing guest os.

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10040.py

JIRA[ELPPCKVM-820]:Update case rhel7_10040

JIRA[ELPPCKVM-820]:Update case rhel7_10040

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10078.py

JIRA[ELPPCKVM-810]:Add the Polarion case rhel7_10078

JIRA[ELPPCKVM-810]:Add the Polarion case rhel7_10078

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10075.py

JIRA[ELPPCKVM-821]:Add the Polarion case rhel7_10075

JIRA[ELPPCKVM-821]:Add the Polarion case rhel7_10075

---

vm.py

ELPPCKVM-830: [framework] Delete the function check_err_info in vm.py

ELPPCKVM-830: [framework] Delete the function check_err_info in vm.py

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10055.py

update case rhel7_10055.py code

update case rhel7_10055.py code

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10056.py

JIRA[ELPPCKVM-828]:Add the polarion case rhel7_10056

JIRA[ELPPCKVM-828]:Add the polarion case rhel7_10056

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10061.py

JIRA[ELPPCKVM-826]:Add the polarion case rhel7_10061

JIRA[ELPPCKVM-826]:Add the polarion case rhel7_10061

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10056.py

JIRA[ELPPCKVM-832]:Update case rhel7_10056

JIRA[ELPPCKVM-832]:Update case rhel7_10056

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10061.py

JIRA[ELPPCKVM-833]:Update case rhel7_10061

JIRA[ELPPCKVM-833]:Update case rhel7_10061

---

utils_params.py

ELPPCKVM-824: [framework] Add { }  for variable function in yaml

---

vm.py

ELPPCKVM-827: [framework] Update the function reader() in vm.py

---

vm.py

Disable the way of check the error of qemu cli output.

ELPPCKVM-827-V2: [framework] Update the function reader() in vm.py.

---

c_scripts/migration_dirtypage_1.c
c_scripts/migration_dirtypage_2.c

[Framework]Add two c scripts for migration cases
migration_dirtypage_1.c and migration_dirtypage_2.c

[Framework]Add two c scripts for migration cases

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10064.py

update case rhel7_10064.py code

update case rhel7_10064.py code

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10068.py

update case rhel7_10068.py code

update case rhel7_10068.py code

---

virtkvmqe/migration_test_plan/migration/test_requirement/ppc64le/rhel7_58700.yaml
virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114.yaml

ELPPCKVM-849: [framework] add case name in rhel7_47114 and rhel7_58700.

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10035.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10056.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10061.py

[Migration]modify some int paras to string for qmp
rhel7_10035,rhel7_10056,rhel7_10061

[Migration]modify some int paras to string for qmp

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10067.py

JIRA[ELPPCKVM-850]:Add the polarion case rhel7_10067
[migration] Set migration downtime

JIRA[ELPPCKVM-850]:Add the polarion case rhel7_10067

---

utils_host.py
vm.py

ELPPCKVM-855: [framework] update the host scp function in utils_host.py

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10047.py

JIRA[ELPPCKVM-854]:Add the polarion case rhel7_10047
Ping-pong live migration with large vcpu and memory values of guest

JIRA[ELPPCKVM-854]:Add the polarion case rhel7_10047

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_59369.py

JIRA[ELPPCKVM-853]:Add the polarion case rhel7_59369
Migrate guest after hotpluging vcpu - ppc only

JIRA[ELPPCKVM-853]:Add the polarion case rhel7_59369

---

utils_host.py

RA[ELPPCKVM-858]:update utils_host.py: get_guest_pid()

RA[ELPPCKVM-858]:update utils_host.py: get_guest_pid()

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10044.py

JIRA[ELPPCKVM-839]:Add the polarion case rhel7_10044 
[migration] Verify migration down time

JIRA[ELPPCKVM-839]:Add the polarion case rhel7_10044

---

virtkvmqe/migration_test_plan/migration/test_requirement/ppc64le/rhel7_58700.yaml
virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114.yaml

JIRA[ELPPCKVM-836] update the rhe7_47114.yaml and rhel7_58700.yaml

JIRA[ELPPCKVM-836] update the rhe7_47114.yaml and rhel7_58700.yaml

---

vm.py

ELPPCKVM-827-V3: [framework] Update the function reader() in vm.py

---

utils_guest.py
utils_host.py
vm.py

e.g:
[root@host ~]#
[root@guest ~]#

ELPPCKVM-864: [framework] add the prompt of host and guest command.

---

monitor.py
virtkvmqe/migration_test_plan/migration/test_requirement/ppc64le/rhel7_58700.yaml
virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114.yaml
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10027.py

[migration] Do live migrate during vm boot .

ELPPCKVM-859: [Migration]Add the polarion case rhel7_10027

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10026.py

JIRA[ELPPCKVM-868]:Update case rhel7_10026

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10070.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10071.py

JIRA[ELPPCKVM-873]:Update case rhel7_10070 and rhel7_10071

JIRA[ELPPCKVM-873]:Update case rhel7_10070 and rhel7_10071

---

virtkvmqe/migration_test_plan/migration/test_requirement/ppc64le/rhel7_58700.yaml
virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114.yaml
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10072.py

JIRA[ELPPCKVM-867]:Add the polarion case rhel7_10072
[migration] Migrate guest during VM installation - scenario2 - formatting disk

JIRA[ELPPCKVM-867]:Add the polarion case rhel7_10072

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10057.py

update case rhel7_10057 code

---

virtkvmqe/migration_test_plan/migration/test_requirement/ppc64le/rhel7_58700.yaml
virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114.yaml

add case rhel7_10057 to rhel7_47114.yaml and rhel7_58700.yaml

add case rhel7_10057 to rhel7_47114.yaml and rhel7_58700.yaml

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10062.py

update case rhel7_10062 code

---

monitor.py
runner.py
utils_guest.py
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/ppc64le/rhel7_51215_matrix_virtio_scsi_iscsi.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/ppc64le/rhel7_51215_matrix_virtio_scsi_local.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_scenarios/rhel7_11912_virtio_scsi_local.py
vm.py

Fix the issue of high cpu loader.

ELPPCKVM-847: [framework] Usage of rate of Start2Run over 150%!!

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10022.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10026.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10027.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10031.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10035.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10039.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10040.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10044.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10047.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10052.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10055.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10056.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10057.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10059.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10061.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10062.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10064.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10067.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10068.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10070.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10071.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10075.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10078.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_59369.py

JIRA[ELPPCKVM-876]:Update case

---

monitor.py

ELPPCKVM-888: [framework] update monitor.py !!!!

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_59369.py

fix rhel7_59369

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10055.py

fix rhel7_10055

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10064.py

fix rhel7_10064

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10068.py

fix rhel7_10068

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10078.py

fix rhel7_10078

---

utils_migration.py

fix ping_pong_migration()

---

monitor.py

ELPPCKVM-888-V2: [framework] update monitor.py !!!!

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10061.py

ELPPCKVM-891-rhel7_10061: [migration] update and review migration case.

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10064.py

ELPPCKVM-891-rhel7_10064: [migration] update and review migration case.

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10067.py

ELPPCKVM-891-rhel7_10067: [migration] update and review migration case.

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10047.py

ELPPCKVM-891-rhel7_10047: [migration] update and review migration case.

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10040.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10044.py

ELPPCKVM-891-rhel7_10044-rhel7_10040: [migration] update and review migration case.

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10022.py

ELPPCKVM-891-rhel7_10022: [migration] update and review migration case.

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10078.py

ELPPCKVM-891-rhel7_10078: [migration] update and review migration case.

---

runner.py
utils_options.py
virtkvmqe/migration_test_plan/migration/test_requirement/ppc64le/rhel7_58700.yaml
virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/ppc64le/rhel7_51215_matrix_virtio_scsi_iscsi.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/ppc64le/rhel7_51215_matrix_virtio_scsi_local.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/x86_64/rhel7_58986_matrix_virtio_scsi_iscsi.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/x86_64/rhel7_58986_matrix_virtio_scsi_local.yaml
vm.py

add the option --repeat_times and update the method of log named.

ELPPCKVM-890: [framework] Add a option --repeat_times on Start2Run.py.

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10057.py

2018-04-16-06:19:24: {"timestamp":{"seconds": 1523873961, "microseconds": 657129}, "event": "STOP"}
2018-04-16-06:19:27: {"execute":"query-migrate"}
2018-04-16-06:19:28: Case Error: Failed to run {"execute":"query-migrate"}under 1.0 sec

JIRA[ELPPCKVM-899]:Fix case rhel7_10057

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10064.py

JIRA[ELPPCKVM-902]:Fix case rhel7_10064

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10061.py

JIRA[ELPPCKVM-901]:Fix case rhel7_10061

---

monitor.py
virtkvmqe/migration_test_plan/migration/test_requirement/ppc64le/rhel7_58700.yaml
virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114.yaml

ELPPCKVM-898: [migration] fix issue of "Failed to login under 10 sec after type user and password"

ELPPCKVM-898: [migration] fix issue of "Failed to login under 10 sec after type user and password"

---

monitor.py
runner.py
utils_options.py
utils_params.py
vm.py

ELPPCKVM-910: [framework] fix the issus that can't shutdown -h now.

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10070.py

JIRA[ELPPCKVM-908]:Fix case rhel7_10070

---

vm.py

ELPPCKVM-811: [framework] Update Python 2&3 compatible code

---

runner.py

ELPPCKVM-811-v2: [framework] Update Python 2&3 compatible code

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10031.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10044.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10062.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10078.py

JIRA[ELPPCKVM-909]:Fix 10062, 10078, 10044 and 10031: serial to seeion

---

utils_guest.py

ELPPCKVM-914: [framework] Replace paramiko with pexpect in GuestSession.

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10047.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10059.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10062.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10070.py

JIRA[ELPPCKVM-919]:fix 10062,10047,10059 10070  dst_serial to src_guest_session

---

utils_migration.py

JIRA[ELPPCKVM-920]:fix qmp STOP

---

Bootstrap-migration.sh
Bootstrap-network.sh
Bootstrap.sh
requirements.txt

delete bootstrap.sh;
add Bootstrap-migration.sh;
add Bootstrap-network.sh;
add Bootstrap.sh;
add requirement.txt.

ELPPCKVM-923-V: [framework] Add a install pip step in bootstrap.sh

---

utils_migration.py
utils_modules.yaml
utils_stable_abi_ppc.py
virtkvmqe/stable_guest_abi_for_ppc_test_plan/ks/RHEL-7-series.ks
virtkvmqe/stable_guest_abi_for_ppc_test_plan/test_requirement/rhel7_109999_p8_p8.yaml
virtkvmqe/stable_guest_abi_for_ppc_test_plan/test_requirement/rhel7_109999_p8_p9.yaml
virtkvmqe/stable_guest_abi_for_ppc_test_plan/test_requirement/rhel7_109999_p9_p9.yaml
virtkvmqe/stable_guest_abi_for_ppc_test_plan/test_scenarios/rhel7_110657.py

[Migration-stable abi ppc]forward and backward migration with “-M pseries-rhel7.5.0” machine type

JIRA[ELPPCKVM-921]:[Migration-stable abi ppc]Add case 110657

---

unattended_installation/unattended_installation.yaml
virtkvmqe/migration_test_plan/migration/test_requirement/ppc64le/rhel7_58700.yaml
virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/ppc64le/rhel7_51215_matrix_virtio_scsi_iscsi.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/ppc64le/rhel7_51215_matrix_virtio_scsi_local.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/x86_64/rhel7_58986_matrix_virtio_scsi_iscsi.yaml

ELPPCKVM-930: [framework] delete the ip of nfs server in all yaml files.

---

utils_options.py

Add some options for command: share_images_dir

ELPPCKVM-812-V2: [framework] Update the option of command "Start2Run"

---

utils_guest.py
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/x86_64/rhel7_58986_matrix_virtio_scsi_local.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_scenarios/rhel7_11911_virtio_scsi_local.py

[virtual block] dd test one disk with different block size - rhel only

Add case :RHEL7-11911

---

virtkvmqe/virtual_block_device_test_plan/virtual_block/test_scenarios/rhel7_11911_virtio_scsi_local.py

Update the case_id.

---

virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/x86_64/rhel7_58986_matrix_virtio_scsi_local.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_scenarios/rhel7_11947_virtio_scsi_local.py

[virtual block] block.cache.writeback/writethrough with I/O + poweroff

Add case: RHEL7-11947

---

monitor.py
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/x86_64/rhel7_58986_matrix_virtio_scsi_local.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_scenarios/rhel7_11948_virtio_scsi_local.py

[virtual block] check the file md5 value steady before and after block_resize

Add case: RHEL7-11948

---

runner.py
unattended_installation/unattended_installation.yaml
utils_options.py
virtkvmqe/migration_test_plan/migration/test_requirement/ppc64le/rhel7_58700.yaml
virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114.yaml
virtkvmqe/stable_guest_abi_for_ppc_test_plan/test_requirement/rhel7_109999_p8_p8.yaml
virtkvmqe/stable_guest_abi_for_ppc_test_plan/test_requirement/rhel7_109999_p8_p9.yaml
virtkvmqe/stable_guest_abi_for_ppc_test_plan/test_requirement/rhel7_109999_p9_p9.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/ppc64le/rhel7_51215_matrix_virtio_scsi_iscsi.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/ppc64le/rhel7_51215_matrix_virtio_scsi_local.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/x86_64/rhel7_58986_matrix_virtio_scsi_iscsi.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/x86_64/rhel7_58986_matrix_virtio_scsi_local.yaml

add options : --nfs_pek_ip, --nfs_bos_ip

ELPPCKVM-812-v5: [framework] Update the option of  command "Start2Run"

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10047.py

free -h | grep Mem | awk '{print $4}' | sed 's/[G,T]//g'

JIRA[ELPPCKVM-942]:[Migration]Fix case rhel7_10047

---

utils_migration.py
utils_options.py
virtkvmqe/migration_test_plan/migration/test_requirement/ppc64le/rhel7_58700.yaml
virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114.yaml
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10044.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10057.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10070.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10071.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10072.py
virtkvmqe/stable_guest_abi_for_ppc_test_plan/test_requirement/rhel7_109999_p8_p8.yaml
virtkvmqe/stable_guest_abi_for_ppc_test_plan/test_requirement/rhel7_109999_p8_p9.yaml
virtkvmqe/stable_guest_abi_for_ppc_test_plan/test_requirement/rhel7_109999_p9_p9.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/ppc64le/rhel7_51215_matrix_virtio_scsi_iscsi.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/ppc64le/rhel7_51215_matrix_virtio_scsi_local.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/x86_64/rhel7_58986_matrix_virtio_scsi_iscsi.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/x86_64/rhel7_58986_matrix_virtio_scsi_local.yaml

[framework] update keyword "image1_name" to "sys_image_name"

ELPPCKVM-944:[framework] update keyword "image1_name" to "sys_image_name"

---

README

JIRA[ELPPCKVM-943]:[Framework]Modify README

---

Bootstrap-migration.sh
Bootstrap.sh

[framework] Updae Bootstrap.sh and Bootstrap-migration.sh
1.pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
2. add mkdir share image dir on dst host
3. scp qemu script to dst host.
4. yum install bridge-utils on dst host.

ELPPCKVM-946: [framework] Updae Bootstrap.sh and Bootstrap-migration.sh

---

unattended_installation/unattended_installation.py

ELPPCKVM-948: [framework] update unattended_installation.py

---

utils_misc.py

Management common  or misc function api.

ELPPCKVM-950: [framework] add utils_misc.py

---

README

JIRA[ELPPCKVM-952]:[Framework]Update README: delete internal host ip addr

JIRA[ELPPCKVM-952]:[Framework]Update README: delete internal host ip addr

---

utils_migration.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10047.py

JIRA[ELPPCKVM-945]:[Migration]Fix case rhel7_10047 about "-smp 0" and migration timeout

---

monitor.py

ELPPCKVM-888-v2:[framework] update monitor.py

---

unattended_installation/ks/RHEL-7-series.ks
virtkvmqe/stable_guest_abi_for_ppc_test_plan/ks/RHEL-7-series.ks

ELPPCKVM-954: [framework] delete the baseurl in ks file.

---

virtkvmqe/migration_test_plan/migration/ks/RHEL-7-series.ks

ELPPCKVM-954-v2: [framework] delete the baseurl in ks file.

---

virtkvmqe/stable_guest_abi_for_ppc_test_plan/test_requirement/rhel7_109999_p8_p8.yaml
virtkvmqe/stable_guest_abi_for_ppc_test_plan/test_requirement/rhel7_109999_p8_p9.yaml
virtkvmqe/stable_guest_abi_for_ppc_test_plan/test_requirement/rhel7_109999_p9_p9.yaml

JIRA[ELPPCKVM-957]:Fix bug about stable yaml of chinese ""

---

utils_migration.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10027.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10056.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10057.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10061.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10062.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10067.py

JIRA[ELPPCKVM-953]:Fix bug about parameter of do_migration: chk_timeout

---

virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114_win.yaml
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10022_win.py

Signed-off-by: Yumei Huang <yuhuang@redhat.com>

JIRA[ELPPCKVM-961]: [migration] add case rhel7_10022_win

---

monitor.py
utils_guest.py
utils_host.py
utils_iscsi.py
utils_misc.py
utils_session.py
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_requirement/x86_64/rhel7_58986_matrix_virtio_scsi_local.yaml
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_scenarios/rhel7_11911_virtio_scsi_local.py
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_scenarios/rhel7_11947_virtio_scsi_local.py
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_scenarios/rhel7_11948_virtio_scsi_local.py
virtkvmqe/virtual_block_device_test_plan/virtual_block/test_scenarios/rhel7_11949_virtio_scsi_local.py
vm.py

ELPPCKVM-959: [Framework] add iscsi backend.

---

utils_host.py
utils_iscsi.py

ELPPCKVM-959-v2: [Framework] add iscsi backend.

---

utils_migration.py
utils_stable_abi_ppc.py

[Migration]update utils_migration.py and utils_stable_abi_ppc.py

[JIRA]:ELPPCKVM-947:[Migration]update utils_migration.py and utils_stable_abi_ppc.py

---

monitor.py
utils_misc.py

1.add "id" for qmp command
modify monitor.py and utils_misc.py
2.fix bug for stable abi
{"return": {"status": "failed", "error-desc": "Failed to connect socket: Connection refused"}, "id": "rgqiiB45"}

JIRA[ELPPCKVM-960]:[Framework]Add "id" to qmp command

---

virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10022.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10031.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10035.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10044.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10055.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10056.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10057.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10059.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10061.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10062.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10064.py
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10067.py

10022:
due to update of host_cmd_output()
10059:
it's wrong in logic about reboot vm in step5
some cases about stress tools

JIRA[ELPPCKVM-963]:[Migration]Update case rhel7_10022 and rhel7_10059 and other cases about stress tools

---

virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114_win.yaml
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10075_win.py

Signed-off-by: Yumei Huang <yuhuang@redhat.com>

ELPPCKVM-969: [Migration]Add case rhel7_10075_win

---

monitor.py

ELPPCKVM-958: [Framework]Failed to get guest ip

---

utils_migration.py
utils_modules.yaml
virtkvmqe/migration_test_plan/postcopy/test_requirement/ppc64le/rhel7_49060_ppc.yaml
virtkvmqe/migration_test_plan/postcopy/test_requirement/x86_64/rhel7_49060_win.yaml
virtkvmqe/migration_test_plan/postcopy/test_requirement/x86_64/rhel7_49060_x86.yaml
virtkvmqe/migration_test_plan/postcopy/test_scenarios/rhel7_49062.py
virtkvmqe/migration_test_plan/postcopy/test_scenarios/rhel7_85702.py

JIRA[ELPPCKVM-971]:[postcopy]Add polarion case rhel7_49062 and rhel7_85702

---

virtkvmqe/migration_test_plan/migration/test_requirement/x86_64/rhel7_47114_win.yaml
virtkvmqe/migration_test_plan/migration/test_scenarios/rhel7_10078_win.py

Signed-off-by: Yumei Huang <yuhuang@redhat.com>

ELPPCKVM-980: [Migration]Add polarion case rhel7_10078_win
